---

- hosts: localhost
  vars:
    homebrew_installed_packages:
      - coreutils
      - git
      - gnu-tar
      - jq
      - vim
      - nmap
      - python
      - python3
      - ssh-copy-id
      - tmux
      - wget
      - macvim
      # - {name: macvim, install_options: "with-override-system-vim"}
    homebrew_cask_apps:
      - firefox
      - chrome
      - spotify
  roles:
    - role: homebrew

#  tasks:
#    - name: Install MacVim
#      homebrew:
#        name: macvim
#        install_options: --with-override-system-vim
#        state: latest
