---

- hosts: localhost
  vars:
    homebrew_installed_packages:
      - { name: vim, install_options: "override-system-vim" }
      - nmap
  roles:
    - role: geerlingguy.homebrew

      #  tasks:
      #    - name: Install MacVim
      #      homebrew:
      #        name: macvim
      #        install_options: --with-override-system-vim
      #        state: latest
