---

- hosts: localhost
  vars:
    homebrew_installed_packages:
      - coreutils
      - git
      - gnu-tar
      - jq
      - vim
      - nmap
      - python
      - python3
      - ssh-copy-id
      - tmux
      - wget
      - {name: macvim, install_options: "override-system-vim"}
  roles:
    - role: geerlingguy.homebrew

#  tasks:
#    - name: Install MacVim
#      homebrew:
#        name: macvim
#        install_options: --with-override-system-vim
#        state: latest
